MyAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
# from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import (SpectacularAPIView,
                                   SpectacularRedocView,
                                   SpectacularSwaggerView,)

urlpatterns = [
    # ('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('blog/', include('blogapp.urls')),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemap},
    #     name='django.contrib.sitemaps.views.sitemap',
    # ),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('shopp/', include('shopppCat.urls')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('admin/', admin.site.urls),
    # path('shopp/', include('shopppCat.urls')),

)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import HelloView, MyLogoutView, AboutMeView, ProfileUpdateView, ProfileDetailView, \
    UsersListView, RegisterView, get_cookie_view, set_cookie_view, get_session_view, set_session_view, FooBarView

app_name = 'myauth'

urlpatterns = [
    path('', LoginView.as_view(
        template_name='myauth/login.html',
        redirect_authenticated_user=True,
    ), name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about_me/', AboutMeView.as_view(), name='about'),
    path('about_me/edit', ProfileUpdateView.as_view(), name='about_edit'),
    path('users/<int:pk>',ProfileDetailView.as_view(), name='profile'),
    path('users/', UsersListView.as_view(), name='users'),
    path('register/', RegisterView.as_view(), name='register'),
    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),
    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
]

myauth/models.py
from django.contrib.auth.models import User
from django.db import models

def avatar_directory_path(instance: 'Profile', filename: str) -> str:
    # file will be uploaded to MEDIA_ROOT/avatar/user_<id>/
    # return f'avatar/user_{instance.user.id}/{filename}'
    return 'provile/avatars_{pk}/avatar/{filename}'.format(
        pk=instance.pk,
        filename=filename
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accept = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

# Create your models here.

myauth/forms.py
from django import forms
from myauth.models import Profile, User

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

# class DocumentForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ('avatar',)

class ProfileUpdateForm(forms.ModelForm):
    """
    Форма обновления данных профиля пользователя
    """
    class Meta:
        model = Profile
        fields = ('bio', 'avatar')
    #
    # def __init__(self, *args, **kwargs):
    #     """
    #     Обновление стилей формы обновления
    #     """
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields:
    #         self.fields[field].widget.attrs.update({
    #             'class': 'form-control',
    #             'autocomplete': 'off'
    #         })

myauth/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView
import datetime
from myauth.models import Profile
from .forms import ProfileUpdateForm,UserUpdateForm

# для урока 13.3
from django.utils.translation import gettext as _
# конец

# для урока 13.3
class HelloView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        welcome_mess = _('Hello world')
        return HttpResponse(f'<h1>{welcome_mess}</h1>')
# конец

class AboutMeView(TemplateView):
    template_name = 'myauth/about_me.html'


class UsersListView(ListView):
    # model = Profile
    context_object_name = 'profiles'
    template_name = 'myauth/users_list.html'
    queryset = (
        Profile.objects
        .select_related("user"))

class ProfileDetailView(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'myauth/profile_detail.html'

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name ='myauth/register.html'
    success_url = reverse_lazy('myauth:about')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response


def login_view(request: HttpRequest):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin')

        return render(request,'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin')

    return render(request, 'myauth/login.html', {'error': 'Invalid login'})

class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth/login')


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'myauth/profile_edit.html'

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Редактирование профиля пользователя: {self.request.user.username}'
        if self.request.POST:
            context['user_form'] = UserUpdateForm(self.request.POST, instance=self.request.user)
        else:
            context['user_form'] = UserUpdateForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context['user_form']
        if all([form.is_valid(), user_form.is_valid()]):
            user_form.save()
            form.save()
        else:
            context.update({'user_form': user_form})
            return self.render_to_response(context)
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('myauth:about')

# def logout_view(request: HttpRequest):
#     logout(request)
#     return redirect(reverse('myauth/login'))

def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fuxx', 'buzz', max_age=3600)
    return response

def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fuxx', 'default value')
    return HttpResponse(f'Cookie value: {value}')

@permission_required('yauth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spasae'
    return HttpResponse('Session set!')

@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default value')
    return HttpResponse(f'Session value {value}')

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar'})

myauth/templates/myauth/about_me.html
{% extends 'myauth/base.html' %}

{% block title %}
About me
{% endblock %}

{% block body %}

    <h1>User info</h1>

        <h2>Detail</h2>
        {% if user.profile.avatar %}
            <p><img src="{{user.profile.avatar.url}}" alt="avatar"></p>
        {% else %}
            no avatar
        {% endif %}
            {% if user.is_staff or request.user == user.profile.user %}
                <p></p><a href="{% url 'myauth:about_edit' %}">Редактировать профиль</a></p>
            {% endif %}
        <p>Username: {{user.username}}</p>
        <p>First name: {{user.firs_name}}</p>
        <p>Last name: {{user.last_name}}</p>
        <p>Email: {{user.email}}</p>
        <p>Bio: {{user.profile.bio}}</p>



{% endblock %}

myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block body %}

{% endblock %}

</body>
</html>

myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Login</button>
</form>
{% endblock %}

myauth/templates/myauth/profile_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
Пользователь
{% endblock %}

{% block body %}
<div>
        <div>
            <div>
                <figure>
                    <img src="{{ profile.avatar.url }}" alt="{{ profile }}">
                </figure>
                <div>
                    <div>
                        <ul>
                            <li>Имя {{ profile.user.username }}</li>
                            <li>О себе: {{ profile.bio }}</li>
                        </ul>

                    </div>
                </div>
                <a href="{% url 'myauth:users' %}">
            Back to list
                </a>

            </div>
        </div>
    </div>
{% endblock %}

myauth/templates/myauth/profile_edit.html
{% extends 'myauth/base.html' %}

{% block title %}
Edit
{% endblock %}

{% block body %}
<div>
   <div>
      <div>
         <h4>Изменение профиля</h4>
      </div>
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ user_form.as_p }}
         {{ form.as_p }}
         <div>
            <button type="submit">Подтвердить изменение профиля</button>
         </div>
      </form>
   </div>
</div>
{% endblock %}

myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

myauth/templates/myauth/users_list.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
<h1>Users:</h1>
    {% if not object_list %}
        <h3>Not order yet</h3>
    {% else %}
        <div>{% for elem in profiles  %}</div>
            <p><a href="{% url 'myauth:profile' pk=elem.pk %}">Details # {{ elem.user.username }}</a></p>
            {% endfor %}
    {% endif %}
{% endblock %}