MyAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
# from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import (SpectacularAPIView,
                                   SpectacularRedocView,
                                   SpectacularSwaggerView,)

urlpatterns = [
    # ('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('blog/', include('blogapp.urls')),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemap},
    #     name='django.contrib.sitemaps.views.sitemap',
    # ),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('shopp/', include('shopppCat.urls')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('admin/', admin.site.urls),
    # path('shopp/', include('shopppCat.urls')),

)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

shopppCat/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ShopIndexView,
                    GroupsListView,
                    ProductDetailsView,
                    ProductListView,
                    OrderDetailsView,
                    ProductUdateView,
                    ProductCreateView,
                    OrderUdateView,
                    ProductDeleteView,
                    LatestProductsFeed,
                    UserOrdersListView,
                    OrderDeleteView,
                    OrderExportView,
                    OrderListView, index_upload,
                    OrderCreateView, ProductViewSet, OrderViewSet)

app_name = 'shopppCat'

routers = DefaultRouter()
routers.register(r'products', ProductViewSet)
routers.register(r'orders', OrderViewSet)


urlpatterns = [
    path('', ShopIndexView.as_view(), name='index_shop'),
    path('api/', include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='group-list'),

    # пути для Практической работы 19.6
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_order_list'),
    path('users/<int:user_id>/orders/export', UserOrdersListView.as_view(), name='user_order_list'),

    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product-details'),
    path('products/<int:pk>/update', ProductUdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete', ProductDeleteView.as_view(), name='delete'),
    path('products/create', ProductCreateView.as_view(), name='create_prod'),
    path('products/latest/feed',LatestProductsFeed(), name='product-feed'),
    path('orders/', OrderListView.as_view(), name='order'),
    path('orders/export', OrderExportView.as_view(), name='order-export'),
    path('orders/create', OrderCreateView.as_view(), name='create_order'),
    path('orders/<int:pk>/', OrderDetailsView.as_view(), name='order-detail'),
    path('orders/<int:pk>/update', OrderUdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete', OrderDeleteView.as_view(), name='order_delete'),
    path('upload/', index_upload, name='upload'),

]

shopppCat/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _

class Product (models.Model):
    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')


    name = models.CharField(max_length=100)
    discription = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    createt_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    arhivate = models.BooleanField(default=False)

    @property
    def descrip_short(self)-> str:
        if len(self.description)<48:
            return self.description
        return self.description[:48] + '...'

    def __str__(self)->str:
        return f"Product(pk={self.pk}, name={self.name!r}"

    def get_absolute_url(self):
        return reverse('shopppCat:product_det',kwargs={'pk': self.pk})

class Order (models.Model):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(blank=True, null=True,)
    promo_code = models.CharField(max_length=100, null=True,blank=True)
    createt_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    # receipt = models.FileField(null=True, upload_to='orders/receipt')

shopppCat/forms.py
from django import forms
from .models import Product, Order
from django.contrib.auth.models import Group
from django.forms import ModelForm

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'discription', 'price', 'discount'


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address', 'promo_code', 'products', 'user'

shopppCat/views.py
import logging
from timeit import default_timer

from django.contrib.syndication.views import Feed
from rest_framework.decorators import action
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import View
from django.contrib.auth.models import Group, User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.core.cache import cache
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from .serializers import ProductSerializer, OrderSerializer
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from drf_spectacular.utils import extend_schema

from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order

log = logging.getLogger(__name__)

class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    fiterset_fields = [
        'name', 'discription', 'price', 'discount'
    ]
    search_fields = [
        'name', 'discription'
    ]
    ordering = 'pk','name'


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    fiterset_fields = [
        'createt_at, '
        'user',
    ]
    search_fields = [
        'createt_at, '
        'user',
    ]
    ordering = 'pk','createt_at'

class ShopIndexView(View):
    def get(self, request:HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 199),
            ('Smatphone', 500),
            ('Desktop', 350),
        ]
        context = {
            'time_run': default_timer(),
            'products': products
        }
        return render(request, 'shopppCat/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.all(),
        }
        return render(request, 'shopppCat/group-list.html', context=context)

    def post(self, request:HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = "shopppCat/product-details.html"
    model = Product
    context_object_name = "products"


class ProductListView(ListView):
    template_name = 'shopppCat/products_list.html'
    # model = Product
    context_object_name = 'products'
    queryset = Product.objects.all


class ProductCreateView(PermissionRequiredMixin,CreateView):
    permission_required = 'shopppCat.add_product'
    model = Product
    fields = 'name', 'price', 'discount', 'discription'
    success_url = reverse_lazy('shopppCat:product_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user

        return super().form_valid(form)

class ProductUdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.reqest.user
        return self.request.user.is_superoser or user.has_perm('shopppCat.add_product') or Product.created_by == user

    model = Product
    fields = 'name', 'price', 'discount', 'discription'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopppCat:product_det',
            kwargs={'pk': self.object.pk}
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopppCat:product_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.arhivate = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class LatestProductsFeed(Feed):
    title = 'Latest Products'
    description = 'Latest Products'
    link = reverse_lazy('shopppCat:product_list')

    def items(self):
        return Product.objects.all()[:5]

    def item_title(self, item):
        return item.name

    def item_description(self, item):
        return item.discription

    def item_link(self, item):
        return reverse('shopppCat:product_det', kwargs={'pk': item.pk})

class OrderListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related('products')
    )


class OrderDetailsView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopppCat.view_order'
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related('products')
    )


class OrderCreateView(CreateView):
    model = Order
    fields = 'delivery_address', 'promo_code', 'user', 'products'
    success_url = reverse_lazy('shopppCat:order')


class OrderUdateView(UpdateView):
    model = Order
    fields = 'delivery_address', 'promo_code', 'user', 'products'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopppCat:order-detail',
            kwargs={'pk': self.object.pk}
        )

class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopppCat:order')


def index_upload (request:HttpRequest)->HttpResponse:
    if request.method =='POST' and request.FILES.get('myfile'):
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        file_size = fs.size(myfile)
        if file_size >= 1048576:
            return render(request, 'shopppCat/error.html')
        else:
            filename = fs.save(myfile.name, myfile)
            print('save!', filename)
    return render(request, 'shopppCat/upload.html')


class OrderExportView(View):
    def get(self, request:HttpRequest) -> JsonResponse:
        order = Order.objects.order_by("pk").all()
        order_data = [
            {
                'pk': order.pk,
                'delivery_address': order.delivery_address,
                'promo_code': order.promo_code,
                'user': order.user,
                'products': order.products
            }
            for order in order
        ]
        return JsonResponse({'order': order_data})


# Классы для Практической работы 19.6
class UserOrdersListView(ListView):
    template_name = 'shopppCat/user_orders.html'
    context_object_ = 'user_orders'

    def get_queryset(self, **kwargs):
        ower = get_object_or_404(User, pk=self.kwargs['user_id'])
        orders = Order.objects.filter(user=ower).all()
        context = {
            'USER': ower,
            'orders': orders,
        }
        return context

    def get_context_data(self, **kwargs):
        context = super(UserOrdersListView, self).get_context_data(**kwargs)
        return context
class User_OrderExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        order_data = cache.get(
            f'order_{self.kwargs["user_id"]}'
        )
        if order_data is None:
            ower = get_object_or_404(User, pk=self.kwargs['user_id'])
            order = Order.objects.filter(user=ower).all()
            order_data = [
                {
                    'pk': order.pk,
                    'delivery_address': order.delivery_address,
                    'promo_code': order.promo_code,
                    'user': order.user,
                    'products': order.products
                }
                for order in order
            ]
            cache.set(
                f'order_{ower.pk}',
                order_data,
                timeout=60
            )
        return JsonResponse({'order': order_data})

shopppCat/templates/shopppCat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block body %}

{% endblock %}

<div>
    {% now 'H:i' %}
</div>
<div>
    HTTP User-Agent {{ request.user_agent }}
</div>
</body>
</html>

shopppCat/templates/shopppCat/create_Order.html
{% extends 'shopppCat/base.html' %}

{% block title %}
Create Prod
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
      <form method="post">
        {% csrf_token %}

          {{ form1.as_p}}
        <button type="submit">Create</button>
      </form>
    </div>

    <div>
      <a href="{% url 'shopppCat:order' %}">
                back to list
      </a>
    </div>
{% endblock %}

shopppCat/templates/shopppCat/create_Prod.html
{% extends 'shopppCat/base.html' %}

{% block title %}
Create Prod
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
      <form method="post">
        {% csrf_token %}

          {{ form.as_p}}
        <button type="submit">Create</button>
      </form>
    </div>

    <div>
      <a href="{% url 'shopppCat:product_list' %}">
                back to list
      </a>
    </div>
{% endblock %}

shopppCat/templates/shopppCat/group-list.html
{% extends 'shopppCat/base.html' %}

{% block title %}
Group List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
                {{ form }}
            <button type="submit">Create</button>
        </form>

    </div>
<div>
    {% if not groups %}
        <h3>Not groups yet</h3>
    {% else %}
        <ul>
            {% for elem in groups  %}
            <li>{{ elem.name }}

            </li>
            {% endfor %}
        </ul>
    {% endif %}

</div>
{% endblock %}

shopppCat/templates/shopppCat/order_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
<li>
    <a href="{% url 'admin:import_order_csv' %}" class="addlink">
        Import CSV
    </a>
</li>
{{ block.super }}
{% endblock %}

shopppCat/templates/shopppCat/order_confirm_delete.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Delete {{ object.name }}
{% endblock %}

{% block body %}
<h2>Delete? {{ object.name }}</h2>
<div>
 <a href="{% url 'shopppCat:order-detail' pk=object.pk%}">
                back product #{{ object.pk }}
      </a>
</div>
    <div>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>

{% endblock %}

shopppCat/templates/shopppCat/order_detail.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
<h1>Order #{{ object.pk }}</h1>
            <p>Order by {% firstof object.user.first_name object.user.username  %}</p>
            <p> Deliv Addres: {{ object.delivery_address }}</p>
            <p> Promo: {{ object.promo_code }}</p>
        <ul>
            {% for product in object.products.all %}
                <li>{{ product.name }} for {{ product.price }}</li>
            {% endfor %}
        </ul>

    <div>
        <p>
          <a href="{% url 'shopppCat:order_update' pk=order.pk %}">edit</a>
        </p>
    </div>
    <div>
        <p>
          <a href="{% url 'shopppCat:order_delete' pk=order.pk %}">delete</a>
        </p>
    </div>
    <div>
        <a href="{% url 'shopppCat:order' %}">
            Back to list
        </a>
    </div>

{% endblock %}

shopppCat/templates/shopppCat/order_update_form.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Edit order
{% endblock %}

{% block body %}
    <h1>Edit order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Edit</button>
        </form>
    </div>
    <div>
      <p><a href="{% url 'shopppCat:order-detail' pk=object.pk%}">
                back order #{{ object.pk }}
      </a></p>

    </div>
{% endblock %}

shopppCat/templates/shopppCat/product-details.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Product # {{ products.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ products.name }}</strong></h1>
    <div>Description: {{ products.discription }}</div>
    <div>Price: {{ products.price }}</div>
    <div>Discount: {{ products.discount }}</div>
    <div>Arhived: {{ products.arhivate }}</div>
    <div>
        <p>
          <a href="{% url 'shopppCat:product_update' pk=products.pk %}">edit</a>
        </p>
    </div>
    <div>
        <p>
          <a href="{% url 'shopppCat:delete' pk=products.pk %}">delete</a>
        </p>
    </div>
    <div>
        <p>
           <a href="{% url 'shopppCat:product_list' %}">Back to list</a>
        </p>
    </div>
{% endblock %}

shopppCat/templates/shopppCat/product_detail.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Product # {{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>Description: {{ product.description }}</div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Arhived: {{ product.arhived }}</div>
    <div>
        <a href="">edit</a>
    </div>
    <div>
        <a href="{% url 'shopppCat:product_list' %}">Back to list</a>
    </div>
{% endblock %}

shopppCat/templates/shopppCat/product_form.html
{% extends 'shopppCat/base.html' %}

{% block title %}
    Create Product
{% endblock %}

{% block body %}
    <h1>CReate product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
      <a href="{% url 'shopppCat:product_list' %}">
                back to list
      </a>
    </div>
{% endblock %}

shopppCat/templates/shopppCat/products_list.html
{% extends 'shopppCat/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'shopppCat:create_prod' %}">{% translate 'New product' %}</a>
    </div>
<h1>{% translate "Products" %}:</h1>
        {% if not products %}
            <h3> Not products yet </h3>
        {% else %}
                {% blocktranslate count products_count=products|length %}
                    {% plural %}
                    There are {{ products_count }} products
                {% endblocktranslate %}
            <div>{% for elem in products  %}</div>

                    <p><a href="{% url 'shopppCat:product-details' pk=elem.pk %}">{% translate 'Name' %}: {{ elem.name }}</a></p>
                    <p> {% translate 'Discription' %}: {{ elem.discription }}</p>
                    <p>{% translate 'Price' %} {{ elem.price }}</p>
                    <p>{% translate 'Discount' %} {{ elem.discount }}</p>

                {% endfor %}

        {% endif %}

{% endblock %}

shopppCat/templates/shopppCat/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload File</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        <input type="file" name="myfile">
    </p>
    <button type="submit">Upload</button>
</form>
</body>
</html>

shopppCat/templates/shopppCat/user_orders.html
{% extends 'shopppCat/base.html' %}
{% load cache %}

{% block title %}
<p>User orders list</p>
{% endblock %}

{% block body %}
    {% if orders %}
        {% for order in orders %}
            {% cache 200 ower.id %}
                <p><a href="{% url 'shopppCat:order-detail' pk=elem.pk %}">Details # {{ order.pk }}</a></p>
                <p>Order by {% firstof order.user.username  %}</p>
                <p> Deliv Addres: {{ order.delivery_address }}</p>
                <p> Promo: {{ order.promo_code }}</p>
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for {{ product.price }}</li>
                    {% endfor %}
                </ul>
            {% endcache %}
        {% endfor %}
    {% endif %}
{% endblock %}